/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: ['documentation', 'prerequisite', 'installation', 'upgrading', 'configuration'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'CRUD Generator',
  //     items: ['introduction-CRUD'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Components',
  //     items: ['checkbox', 'code-editor', 'color-picker', 'date', 'date-time', 'editor', 'email', 'hidden', 'number', 'password', 'radio', 'relation', 'search', 'select-multiple', 'select', 'slider', 'switch', 'tags-doc', 'textarea', 'text', 'time', 'upload-file-multiple', 'upload-file', 'upload-image-multiple', 'upload-image', 'url'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Core Concept',
  //     items: ['storage', 'routing', 'role-and-permission'],
  //   },
    // "tutorial-basics/create-a-page",
    // {
    //   type: 'category',
    //   label: 'Basic',
    //   items: ['tutorial-basics/create-a-blog-post',
    //     'tutorial-basics/create-a-document',
    //     'tutorial-basics/create-a-page',
    //     'tutorial-basics/deploy-your-site',
    //     'tutorial-basics/congratulations',]
    // }
  // ],
};
